This is makeindex, version 2.15 [MiKTeX 20.11].
Scanning style file ./Dokumentation.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Dokumentation.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (4 comparisons).
Generating output file Dokumentation.acr....done (12 lines written, 0 warnings).
Output written in Dokumentation.acr.
Transcript written in Dokumentation.alg.
